Bug 1656148 follow-up - Fix errors on compose window opening. r=kaie DONTBUILD
Fixes two errors that happen when the compose window is opened:
TypeError: can't redefine non-configurable property "FileUtils"
ReferenceError: XPCOMUtils is not defined

I caused the first with the previous commit in this bug – this patch undoes part of it. I don't know where the second came from.

Differential Revision: https://phabricator.services.mozilla.com/D85546

--HG--
extra : amend_source : f7b6d4f91dcfc04807e99826dc451af088a080f1
extra : histedit_source : a03439bd17c027de68876267d39c8a45d3fd7302