Bug 1691060 - Add missing function to BasePopup class. r=john.bieling
The test is failing with "TypeError: obj.close is not a function". This is the missing function.

Differential Revision: https://phabricator.services.mozilla.com/D112115

--HG--
extra : moz-landing-system : lando